cleaner_2/amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.25
    alpha2: 0.25
    alpha3: 0.25
    alpha4: 0.25
    alpha5: 0.25
    base_frame_id: "cleaner_2/base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 9000
    min_particles: 500
    odom_frame_id: "cleaner_2/odom"
    pf_err: 0.1
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.25
    update_min_d: 0.3
    z_hit: 0.6
    z_max: 0.05
    z_rand: 0.4
    z_short: 0.05
    scan_topic: "scan"
    map_topic: "/map"
    #set_initial_pose: True
    # starbots_new_edited
    #initial_pose:
    # x: 10.55
    # y: -3.58
    # yaw: 0.0
    # starbots_prod
    # initial_pose:
    #   x: 11.1
    #   y: -4.5
    #   yaw: 0.0

cleaner_2/amcl_map_client:
  ros__parameters:
    use_sim_time: False

cleaner_2/amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False