recoveries_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: map
    local_frame: odom
    robot_base_frame: robot_base_footprint
    transform_timeout: 0.8
    use_sim_time: True
    simulate_ahead_time: 4.0
    max_rotational_vel: 0.65
    min_rotational_vel: 0.30
    rotational_acc_lim: 3.2
    enable_stamped_cmd_vel: False